#!/bin/bash

# Create an admin user
fabmanager create-admin --app superset --username admin --firstname apache --lastname superset --email apache-superset@fab.com --password admin

# Initialize the database
superset db upgrade

# Create default roles and permissions
superset init